apiVersion: v2
name: sei-umbrella
description: Helm chart para subir todos os componentes para o SEI5. Embora seja a abordagem mais rápida, opte por publicar todos os elementos separadamente. Verifique a documentação para melhor entendimento dessa orientação.

type: application

version: 1.0.2

appVersion: "3.6.8"

dependencies:
  - name: sei-app
    version: ">=1.0.0"
    repository: "file://../sei-app"
  - name: sei-db
    version: ">=1.0.0"
    repository: "file://../sei-db"
  - name: sei-jod
    version: ">=1.0.0"
    repository: "file://../sei-jod"
  - name: sei-memcached
    version: ">=1.0.0"
    repository: "file://../sei-memcached"
  - name: sei-solr
    version: ">=1.0.0"
    repository: "file://../sei-solr"
  - name: sei-cacheassets
    version: ">=1.0.0"
    repository: "file://../sei-cacheassets"

icon: https://raw.githubusercontent.com/pengovbr/sei-helm/refs/heads/main/apoio/imagens/seidevlogo.png