apiVersion: v2
name: sei-memcached
description: Helm chart para subir o memcached para o SEI

type: application

version: 1.0.1

appVersion: "3.6.8"

icon: https://raw.githubusercontent.com/pengovbr/sei-helm/refs/heads/main/apoio/imagens/memcachedlogo.png