#orgao: orgaon
memcached:

    # namespace onde roda o memcached, salvo em alguns casos especificos deixe esse valor em branco e informe o namespace pelo helm    
    namespace: ""

    image:
        repository: processoeletronico/memcached
        pullPolicy: IfNotPresent
        tag: ""
    
    nameOverride: ""
    fullnameOverride: ""
